#TESTAR CONEXÃO
GET http://localhost:3333



### Buscar todos os IDs.

GET http://localhost:3333/user/


### Buscar extrato e saldo pelo ID.

GET http://localhost:3333/user/09253516-999e-4453-9d5d-c02105e28c65

### Adicionar Usuário Bruno
POST http://localhost:3333/user/
content-type: application/json

{
    "nome": "Bruno",
    "email": "brunobernardes@gmail.com"
}

### Adicionar Usuário Tiago
POST http://localhost:3333/user/
content-type: application/json

{
    "nome": "Tiago",
    "email": "tiagoalves@gmail.com"
}


### Adicionar Deposito.

PUT  http://localhost:3333/user/deposito/09253516-999e-4453-9d5d-c02105e28c65
content-type: application/json

{
  "tipo": "deposito",
  "valor": 200
}


### Adicionar Retirada.

PUT  http://localhost:3333/user/retirada/09253516-999e-4453-9d5d-c02105e28c65
content-type: application/json

{
  "tipo": "retirada",
  "valor": 100
}



### Deletar Usuário.

DELETE http://localhost:3333/user/09253516-999e-4453-9d5d-c02105e28c65

### Atualizar um usuario pelo ID.

PUT  http://localhost:3333/user/09253516-999e-4453-9d5d-c02105e28c65
content-type: application/json

{
    "nome": "Lucas",
    "email": "tiaguinhograudo@gmail.com"
}
