#TESTAR CONEXÃO
GET http://localhost:3333



### Buscar todos os IDs.

GET http://localhost:3333/user/


### Buscar extrato e saldo pelo ID.

GET http://localhost:3333/user/f62fdd50-fa36-4e55-b504-2ed62102f5e1
### Adicionar Usuário Tiago
POST http://localhost:3333/user/
content-type: application/json

{
    "nome": "Tiago",
    "email": "tiagoalves@gmail.com"
}


### Adicionar Deposito.

PUT  http://localhost:3333/user/deposito/f62fdd50-fa36-4e55-b504-2ed62102f5e1
content-type: application/json

{
  "tipo": "deposito",
  "valor": 200
}


### Adicionar Retirada.

PUT  http://localhost:3333/user/retirada/f62fdd50-fa36-4e55-b504-2ed62102f5e1
content-type: application/json

{
  "tipo": "retirada",
  "valor": 100
}



### Deletar Usuário.

DELETE http://localhost:3333/user/f62fdd50-fa36-4e55-b504-2ed62102f5e1


### Atualizar um usuario pelo ID.

PUT  http://localhost:3333/user/f62fdd50-fa36-4e55-b504-2ed62102f5e1
content-type: application/json
