#TESTAR CONEXÃO
GET http://localhost:3333



### Buscar todos os IDs.

GET http://localhost:3333/user/


### Buscar extrato e saldo pelo ID.

GET http://localhost:3333/user/a9230377-29ce-4002-9cd8-c4c7d30f9c3a

### Adicionar Usuário.
POST http://localhost:3333/user/
content-type: application/json

{
    "nome": "Tiago",
    "saldo": 0,
    "transferencia": [{}]
}


### Adicionar Deposito.

PUT  http://localhost:3333/user/deposito/a9230377-29ce-4002-9cd8-c4c7d30f9c3a
content-type: application/json

{
    "nome": "Tiago",
    "saldo": 0,
    "transferencia": [{
      "tipo": "deposito",
      "valor": 100
    }]
}


### Adicionar Retirada.

PUT  http://localhost:3333/user/retirada/a9230377-29ce-4002-9cd8-c4c7d30f9c3a
content-type: application/json

{
    "nome": "Tiago",
    "saldo": 100,
    "transferencia": [{
      "tipo": "retirada",
      "valor": 100
    }]
}



### Deletar Usuário.

delete http://localhost:3333/user/a9230377-29ce-4002-9cd8-c4c7d30f9c3a

### Atualizar um usuario pelo ID.

PUT  http://localhost:3333/user/a9230377-29ce-4002-9cd8-c4c7d30f9c3a
content-type: application/json

{
    "nome": "Tiago",
    "saldo": 100,
    "transferencia": [{}]
}
